// ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts

import prisma from "../../lib/prisma";

const tags = [
  "React",
  "Vue",
  "Component Toolkit",
  "Testing",
  "Node.js framework",
  "Charting",
  "UI Framework",
  "Learning resource",
  "Angular",
  "GraphQL",
  "Animation",
  "State management",
  "CLI",
  "CSS Toolkit",
  "SVG",
  "Canvas",
  "CSS in JS",
  "Redux",
  "Scrolling",
  "Drag and drop",
  "Cache",
  "Types",
  "3D",
  "React Native",
  "Static site generator",
  "Browser automation",
  "Building tool",
  "Express",
  "Real-time",
  "Video",
  "Web Components",
  "CMS",
  "D3",
  "Markdown",
  "Rich text editor",
  "Image processing",
  "Search",
  "Table",
  "Universal",
  "Autocomplete",
  "Dashboard",
  "Date & time",
  "Game engine",
  "Material design",
  "Compiler",
  "Database",
  "Functional programming",
  "HTTP client / AJAX",
  "Icon set",
  "Machine Learning",
  "Mobile",
  "PDF",
  "Performance",
  "SQL",
  "Scaffolding - generator",
  "Utils",
  "Validation",
  "Virtual DOM",
  "WebGL",
  "Boilerplate",
  "Reactive programming",
  "Slider",
  "Types",
  "Authentication",
  "Desktop app",
  "Form",
  "Full-stack framework",
  "Image viewer",
  "JSON",
  "Layout",
  "Module - bundler",
  "Package - dependency",
  "Plugin / form widget",
  "Accessibility",
  "Audio",
  "Documentation",
  "Drawing",
  "Gesture - Touch",
  "Maps",
  "Math",
  "Microservices",
  "ORM",
  "Web workers",
  "Bootstrap",
  "File system",
  "Fuzzy search",
  "Syntax highlighting",
  "Browser storage",
  "CSS Processor",
  "Colors",
  "Data structure",
  "Diagram / Flow chart",
  "HTML & text parsing",
  "Linter",
  "Middleware",
  "Modal",
  "Notification",
  "Presentation",
  "Routing",
  "Templating",
  "Book",
  "Data fetching",
  "Internationalization i18n",
  "Logging",
  "MongoDB",
  "Offline",
  "Prefetch",
  "Queue",
  "Scraping",
  "Websocket",
  "Runtime",
  "Spreadsheet",
  "Stream",
  "Testing framework",
  "Typography",
  "Web Assembly",
  "Bot",
  "Browser compatibility",
  "Code Editor",
  "Decentralized",
  "Geometry",
  "IDE",
  "Serverless",
  "Svelte",
  "Virtual list",
  "Async flow / Promises",
  "Blockchain",
  "Caching",
  "Email",
  "Format tools",
  "Hook",
  "Input Mask",
  "IoT",
  "Keyboard",
  "Playground",
  "Regular expression",
  "Service Worker",
  "Tooltip",
  "Visual Programming",
  "Blog",
  "Code Parser",
  "Configuration",
  "Debugging",
  "Deno",
  "File upload",
  "Flux",
  "HTML template",
  "Meteor",
  "Money",
  "Monorepo",
  "RPC",
  "Random",
  "State machine",
  "Tour - Guide",
  "Analytics",
  "DOM manipulation",
  "Dev tool",
  "E-commerce",
  "Emoji",
  "Full-text search",
  "Markdown Editor App",
  "Node.js version management",
  "Prerender",
  "Process management",
  "Resource loader",
  "String",
  "Text processing",
  "Virtual Reality",
  "Window management",
  "XML",
  "API wrapper / SDK",
  "Archive",
  "Event sourcing",
  "Font",
  "Menu",
  "Print",
  "Styleguide",
  "Tree / Explorer component",
  "WebRTC",
  "Worker thread",
  "CAD",
  "CSV",
  "Crypto",
  "Crypto-currency",
  "Git",
  "Neural network",
  "Progress bar",
  "Statistics",
  "Workflow automation",
  "Meta",
];

async function main() {
  await prisma.tag.createMany({
    data: tags.map((t) => ({ name: t })),
    skipDuplicates: true,
  });
}

main();
